in alc-system.maude 

mod TEST is
 inc LALC-SYSTEM .

 ops A B C D E : -> AConcept .
 ops R S T U V : -> ARole .

 ops seq : Nat -> Sequent .
 eq seq(1) = < nil | EXIST(S, ALL(R, A)) | nil > |- < nil | EXIST(S, ALL(R, A)) | nil > .
 eq seq(2) = < nil | ALL(S, EXIST(R, A)) | nil > |- < nil | ALL(S, EXIST(R, A)) | nil > .
 eq seq(3) = < nil | EXIST(R, CTRUE) & ALL(R, ~ EXIST(R, ~ A)) | nil > |- < nil | EXIST(R, ALL(R, A)) | nil > .
 eq seq(4) = < nil | A & B | nil > |- < nil | (A | B) | nil > .
 eq seq(5) = < R | A & B | S > |- < R | (A | B) | S > .
 eq seq(6) = < S | A & B | R >, < R | A & B | S > |- < R | (A | B) | S >, < S | (A | B) | R > . 
 eq seq(7) = < R | A | B | S > |- < R | (A & B) | S > .
 
 op start : Sequent -> Goal . 
 eq start(X:Sequent) = [ 0 from 0 by 'init is X:Sequent ] next(1) goals(0) .
 
endm

